// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEHDTPs2LXwK_TlvqbBJXChPeQeH-Pqc',
    appId: '1:618183961246:web:d3fe7ae498da72e460698f',
    messagingSenderId: '618183961246',
    projectId: 'flutterexammehdi',
    authDomain: 'flutterexammehdi.firebaseapp.com',
    storageBucket: 'flutterexammehdi.firebasestorage.app',
    measurementId: 'G-M9T5XWYY4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_2OCBWFVT2XUJvup1La-61Ln4TuaDEI',
    appId: '1:618183961246:android:40a4ef11246e91bf60698f',
    messagingSenderId: '618183961246',
    projectId: 'flutterexammehdi',
    storageBucket: 'flutterexammehdi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYO4ttC96ZSAFHMwWkpzAHPiZQxF4QwLY',
    appId: '1:618183961246:ios:c17ed4f543ffd78060698f',
    messagingSenderId: '618183961246',
    projectId: 'flutterexammehdi',
    storageBucket: 'flutterexammehdi.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYO4ttC96ZSAFHMwWkpzAHPiZQxF4QwLY',
    appId: '1:618183961246:ios:c17ed4f543ffd78060698f',
    messagingSenderId: '618183961246',
    projectId: 'flutterexammehdi',
    storageBucket: 'flutterexammehdi.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXEHDTPs2LXwK_TlvqbBJXChPeQeH-Pqc',
    appId: '1:618183961246:web:bf6000ea197579a860698f',
    messagingSenderId: '618183961246',
    projectId: 'flutterexammehdi',
    authDomain: 'flutterexammehdi.firebaseapp.com',
    storageBucket: 'flutterexammehdi.firebasestorage.app',
    measurementId: 'G-C6ZC7J4RVM',
  );
}
